version: '3.3'

services:
  db:
    image: mysql:latest
    container_name: inventory
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - inventory_db:/var/lib/mysql
    networks:
      - mynet

  app:
    build: .
    container_name: iventory-app
    restart: always
    depends_on:
      - db
    ports:
      - "3002:3000"
    networks:
      - mynet

volumes:
  inventory_db:
    
networks:
  mynet:
