name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: configure directory   
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2112
        script: |
          mkdir -p /var/www/iventory

    - name: Deploy to VPS
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2112
        source: "./*"
        target: /var/www/iventory

    - name: configure database 
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2112
        script: |
          cd /var/www/iventory
          git pull origin main
          docker-compose up -d --build
          docker exec inventori mysql -uuser -p123 -e "INSERT INTO barang (nama, stok, kategori_id) VALUES ('domains', 1000, 01);" iventori
